# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CORBA-MICO
version:      0.6.6
version_from: MICO.pm
installdirs:  site
requires:
    Error:                         0.13

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
